when@dev:
    web_profiler:
        toolbar: true
        excluded_ajax_paths: ^/api

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
